
package net.antra.company.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.4
 * Mon Jan 18 20:49:09 EST 2016
 * Generated source version: 3.1.4
 */

@XmlRootElement(name = "listAllEmployeesResponse", namespace = "http://service.company.antra.net/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "listAllEmployeesResponse", namespace = "http://service.company.antra.net/")

public class ListAllEmployeesResponse {

    @XmlElement(name = "return")
    private java.util.List<net.antra.company.model.Employee> _return;

    public java.util.List<net.antra.company.model.Employee> getReturn() {
        return this._return;
    }

    public void setReturn(java.util.List<net.antra.company.model.Employee> new_return)  {
        this._return = new_return;
    }

}

