
package net.antra.company.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.4
 * Mon Jan 18 20:48:13 EST 2016
 * Generated source version: 3.1.4
 */

@XmlRootElement(name = "updateDepartmentResponse", namespace = "http://service.company.antra.net/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "updateDepartmentResponse", namespace = "http://service.company.antra.net/")

public class UpdateDepartmentResponse {


}

